./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 10 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 11 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 12 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 13 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 14 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 15 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 16 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 17 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 18 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 19 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 20 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 21 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 22 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 23 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 24 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 25 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 26 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 27 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 28 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 29 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 30 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 31 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 32 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 33 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 34 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 35 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 36 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 37 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 38 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 39 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 40 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 41 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 42 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 43 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 44 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 45 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 46 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 47 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 48 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 49 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 50 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 51 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 52 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 53 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 54 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 55 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 56 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 57 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 58 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 59 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 60 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 61 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 62 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 63 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 64 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 65 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 66 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 67 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 68 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 69 -h 10
./facetrain -n test.net -1 ./../trainset/all_test1.list -2 ./../trainset/all_test2.list -t ./../trainset/all_train.list -e 70 -h 10
